[package]
name = "wings_marshal"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description.workspace = true

[dependencies]
bincode.workspace = true
serde.workspace = true
thiserror.workspace = true