[package]
name = "example_plugin"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description.workspace = true

[lib]
crate-type = [ "cdylib" ]

[dependencies]
example_host_system.workspace = true
wings.workspace = true